/** @jsxImportSource https://esm.sh/react@18.2.0 */
// ─── WeeklyAthleteReport.tsx — PDF template for weekly athlete summary ────────
import React from 'https://esm.sh/react@18.2.0'
import { Document, Page, Text, View, StyleSheet } from 'https://esm.sh/@react-pdf/renderer@3.4.4?deps=react@18.2.0'

export interface WeeklyReportData {
  athlete: { display_name: string; email: string }
  weekStart: string        // YYYY-MM-DD (Monday of the week)
  weekEnd:   string        // YYYY-MM-DD (Sunday)
  metrics: {
    ctl:            number
    atl:            number
    tsb:            number
    weekTss:        number
    sessionsCount:  number
    totalDurationMin: number
    avgRpe:         number | null
  }
  sessions: Array<{
    date:         string
    type:         string
    duration_min: number | null
    tss:          number | null
    rpe:          number | null
    notes?:       string | null
  }>
  insights: Array<{
    kind:       string
    content:    string
    created_at: string
  }>
  suggestedFocus?: string
}

const ORANGE = '#ff6600'
const DARK   = '#0a0a0a'
const GREY   = '#666'
const LIGHT  = '#f5f5f5'
const GREEN  = '#2d8c2d'
const RED    = '#c0392b'

const S = StyleSheet.create({
  page: {
    backgroundColor: '#fff',
    paddingTop: 40, paddingBottom: 40,
    paddingLeft: 50, paddingRight: 50,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: '#222',
  },
  header: {
    borderBottom: `2px solid ${ORANGE}`,
    marginBottom: 20,
    paddingBottom: 10,
  },
  title: {
    fontSize: 18, fontWeight: 'bold',
    color: DARK, letterSpacing: 1,
  },
  sub: {
    fontSize: 9, color: GREY, marginTop: 3,
  },
  section: {
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: 11, fontWeight: 'bold', color: ORANGE,
    textTransform: 'uppercase', letterSpacing: 1,
    marginBottom: 8, borderBottom: `1px solid #eee`,
    paddingBottom: 4,
  },
  metricRow: {
    flexDirection: 'row', gap: 12, flexWrap: 'wrap',
    marginBottom: 8,
  },
  metricBox: {
    width: 90, backgroundColor: LIGHT,
    padding: 8, borderRadius: 4,
    alignItems: 'center',
  },
  metricValue: {
    fontSize: 20, fontWeight: 'bold', color: DARK,
  },
  metricLabel: {
    fontSize: 7, color: GREY, textTransform: 'uppercase',
    letterSpacing: 0.5, marginTop: 2,
  },
  tableHeader: {
    flexDirection: 'row', backgroundColor: DARK,
    padding: '5 8', borderRadius: 2,
  },
  tableRow: {
    flexDirection: 'row',
    padding: '5 8',
    borderBottom: '1px solid #f0f0f0',
  },
  tableRowAlt: {
    flexDirection: 'row',
    padding: '5 8',
    backgroundColor: LIGHT,
    borderBottom: '1px solid #f0f0f0',
  },
  th: { fontSize: 8, color: '#fff', fontWeight: 'bold', letterSpacing: 0.5 },
  td: { fontSize: 9, color: '#333' },
  col_date:  { width: '15%' },
  col_type:  { width: '15%' },
  col_dur:   { width: '12%' },
  col_tss:   { width: '10%' },
  col_rpe:   { width: '10%' },
  col_notes: { width: '38%' },
  insightBox: {
    backgroundColor: '#fff8f4', borderLeft: `3px solid ${ORANGE}`,
    padding: 8, marginBottom: 8, borderRadius: 2,
  },
  insightKind: {
    fontSize: 7, color: ORANGE, textTransform: 'uppercase',
    letterSpacing: 0.5, marginBottom: 3,
  },
  insightText: { fontSize: 9, color: '#444', lineHeight: 1.5 },
  focusBox: {
    backgroundColor: '#f0fff4', border: `1px solid ${GREEN}`,
    padding: 12, borderRadius: 4,
  },
  focusText: { fontSize: 10, color: '#2d4a2d', lineHeight: 1.6 },
  footer: {
    position: 'absolute', bottom: 20, left: 50, right: 50,
    flexDirection: 'row', justifyContent: 'space-between',
    borderTop: '1px solid #eee', paddingTop: 6,
  },
  footerText: { fontSize: 7, color: '#bbb' },
})

function tsbColor(tsb: number) {
  if (tsb > 10) return GREEN
  if (tsb < -10) return RED
  return ORANGE
}

function fmt(v: number | null | undefined, dec = 0): string {
  if (v == null || isNaN(v)) return '—'
  return v.toFixed(dec)
}

function fmtDate(iso: string): string {
  try { return iso.slice(0, 10) } catch { return iso }
}

function fmtDur(min: number | null): string {
  if (!min) return '—'
  if (min < 60) return `${min}min`
  return `${Math.floor(min / 60)}h${min % 60 ? `${min % 60}m` : ''}`
}

export function WeeklyAthleteReport({ data }: { data: WeeklyReportData }) {
  const { athlete, weekStart, weekEnd, metrics, sessions, insights, suggestedFocus } = data

  return (
    <Document title={`Weekly Report — ${athlete.display_name} — ${weekStart}`} author="Sporeus">
      {/* ── Page 1: Summary ──────────────────────────────────────────────── */}
      <Page size="A4" style={S.page}>
        <View style={S.header}>
          <Text style={S.title}>WEEKLY TRAINING REPORT</Text>
          <Text style={S.sub}>{athlete.display_name} · {weekStart} — {weekEnd}</Text>
          <Text style={S.sub}>Generated by Sporeus Athlete Console</Text>
        </View>

        {/* Metrics */}
        <View style={S.section}>
          <Text style={S.sectionTitle}>Performance Metrics</Text>
          <View style={S.metricRow}>
            {[
              { label: 'CTL (Fitness)',   val: fmt(metrics.ctl, 1) },
              { label: 'ATL (Fatigue)',   val: fmt(metrics.atl, 1) },
              { label: 'TSB (Form)',       val: fmt(metrics.tsb, 1), color: tsbColor(metrics.tsb) },
              { label: 'Week TSS',         val: fmt(metrics.weekTss) },
              { label: 'Sessions',         val: String(metrics.sessionsCount) },
              { label: 'Total Volume',     val: fmtDur(metrics.totalDurationMin) },
              { label: 'Avg RPE',          val: fmt(metrics.avgRpe, 1) },
            ].map(m => (
              <View style={S.metricBox} key={m.label}>
                <Text style={{ ...S.metricValue, color: m.color || DARK }}>{m.val}</Text>
                <Text style={S.metricLabel}>{m.label}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Form interpretation */}
        <View style={S.section}>
          <Text style={S.sectionTitle}>Form Status</Text>
          <View style={{ padding: 10, backgroundColor: LIGHT, borderRadius: 4 }}>
            <Text style={{ fontSize: 10, color: tsbColor(metrics.tsb), fontWeight: 'bold', marginBottom: 4 }}>
              {metrics.tsb > 10 ? 'FRESH — Ready for high-intensity or race effort'
               : metrics.tsb < -10 ? 'FATIGUED — Recovery recommended before next key effort'
               : 'TRAINED — Balanced state, good for quality sessions'}
            </Text>
            <Text style={{ fontSize: 9, color: GREY, lineHeight: 1.5 }}>
              CTL represents your accumulated training load (fitness). ATL is your recent acute load (fatigue).
              TSB = CTL − ATL; positive TSB indicates freshness, negative indicates fatigue.
            </Text>
          </View>
        </View>

        <View style={S.footer}>
          <Text style={S.footerText}>Sporeus Athlete Console — sporeus.com</Text>
          <Text style={S.footerText} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>

      {/* ── Page 2: Session Table ─────────────────────────────────────────── */}
      <Page size="A4" style={S.page}>
        <View style={S.header}>
          <Text style={S.title}>SESSIONS THIS WEEK</Text>
          <Text style={S.sub}>{sessions.length} session{sessions.length !== 1 ? 's' : ''} logged</Text>
        </View>

        <View style={S.section}>
          {sessions.length === 0 ? (
            <Text style={{ color: GREY, fontSize: 10 }}>No sessions logged this week.</Text>
          ) : (
            <>
              <View style={S.tableHeader}>
                <Text style={{ ...S.th, ...S.col_date }}>Date</Text>
                <Text style={{ ...S.th, ...S.col_type }}>Type</Text>
                <Text style={{ ...S.th, ...S.col_dur }}>Duration</Text>
                <Text style={{ ...S.th, ...S.col_tss }}>TSS</Text>
                <Text style={{ ...S.th, ...S.col_rpe }}>RPE</Text>
                <Text style={{ ...S.th, ...S.col_notes }}>Notes</Text>
              </View>
              {sessions.map((s, i) => (
                <View key={i} style={i % 2 === 0 ? S.tableRow : S.tableRowAlt}>
                  <Text style={{ ...S.td, ...S.col_date }}>{fmtDate(s.date)}</Text>
                  <Text style={{ ...S.td, ...S.col_type }}>{s.type || '—'}</Text>
                  <Text style={{ ...S.td, ...S.col_dur }}>{fmtDur(s.duration_min)}</Text>
                  <Text style={{ ...S.td, ...S.col_tss }}>{fmt(s.tss)}</Text>
                  <Text style={{ ...S.td, ...S.col_rpe }}>{fmt(s.rpe, 1)}</Text>
                  <Text style={{ ...S.td, ...S.col_notes, fontSize: 8 }}
                    numberOfLines={2}>
                    {s.notes || ''}
                  </Text>
                </View>
              ))}
            </>
          )}
        </View>

        <View style={S.footer}>
          <Text style={S.footerText}>Sporeus Athlete Console — sporeus.com</Text>
          <Text style={S.footerText} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>

      {/* ── Page 3: AI Insights ───────────────────────────────────────────── */}
      <Page size="A4" style={S.page}>
        <View style={S.header}>
          <Text style={S.title}>AI COACHING INSIGHTS</Text>
          <Text style={S.sub}>Coach-generated observations this week</Text>
        </View>

        <View style={S.section}>
          {insights.length === 0 ? (
            <Text style={{ color: GREY, fontSize: 10 }}>No AI insights available for this period.</Text>
          ) : (
            insights.slice(0, 5).map((ins, i) => (
              <View key={i} style={S.insightBox}>
                <Text style={S.insightKind}>{ins.kind.replace(/_/g, ' ')} · {fmtDate(ins.created_at)}</Text>
                <Text style={S.insightText}>{ins.content}</Text>
              </View>
            ))
          )}
        </View>

        <View style={S.footer}>
          <Text style={S.footerText}>Sporeus Athlete Console — sporeus.com</Text>
          <Text style={S.footerText} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>

      {/* ── Page 4: Next Week Focus ───────────────────────────────────────── */}
      <Page size="A4" style={S.page}>
        <View style={S.header}>
          <Text style={S.title}>NEXT WEEK SUGGESTED FOCUS</Text>
          <Text style={S.sub}>Based on current training load and form</Text>
        </View>

        <View style={S.section}>
          <View style={S.focusBox}>
            <Text style={S.focusText}>
              {suggestedFocus || deriveDefaultFocus(metrics)}
            </Text>
          </View>
        </View>

        <View style={{ marginTop: 20 }}>
          <Text style={S.sectionTitle}>Training Load Targets</Text>
          <View style={{ flexDirection: 'row', gap: 16 }}>
            {[
              { label: 'Target TSS Range', val: computeTargetTss(metrics) },
              { label: 'Recommended Sessions', val: computeRecommendedSessions(metrics) },
              { label: 'Intensity Balance', val: computeIntensityBalance(metrics) },
            ].map(m => (
              <View key={m.label} style={{ ...S.metricBox, width: 140 }}>
                <Text style={{ fontSize: 12, fontWeight: 'bold', color: DARK }}>{m.val}</Text>
                <Text style={S.metricLabel}>{m.label}</Text>
              </View>
            ))}
          </View>
        </View>

        <View style={S.footer}>
          <Text style={S.footerText}>Sporeus Athlete Console — sporeus.com</Text>
          <Text style={S.footerText} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>
    </Document>
  )
}

// ── Pure helpers ──────────────────────────────────────────────────────────────

function deriveDefaultFocus(m: WeeklyReportData['metrics']): string {
  if (m.tsb < -20) return 'Focus on active recovery this week. Your fatigue levels are elevated. Limit intensity to Z1/Z2, prioritize sleep and nutrition. A reduced load week will rebuild your form for the next training block.'
  if (m.tsb > 20)  return 'You are very fresh — consider a moderate build this week. Your form is excellent; this is a good time for quality sessions. Aim for 1–2 threshold or VO2max workouts alongside your easy aerobic base.'
  if (m.tsb > 5)   return 'Good form balance. Consider a productive week with 1 quality session (threshold or interval) and 3–4 easy aerobic sessions. Monitor RPE — if fatigue accumulates, back off intensity.'
  return 'Maintain your current training rhythm. Your CTL is building steadily. Focus on consistency: 4–5 sessions with at least one quality effort. Ensure adequate sleep and recovery between sessions.'
}

function computeTargetTss(m: WeeklyReportData['metrics']): string {
  const base = Math.round(m.weekTss * 1.05)
  return `${Math.max(0, base - 20)}–${base + 20}`
}

function computeRecommendedSessions(m: WeeklyReportData['metrics']): string {
  if (m.tsb < -10) return '3–4 (easy)'
  if (m.tsb > 15)  return '4–5 (build)'
  return '4–5 sessions'
}

function computeIntensityBalance(m: WeeklyReportData['metrics']): string {
  if (m.tsb < -10) return '90% Z1/Z2, 10% Z3'
  return '80% Z1/Z2, 20% Z3–Z5'
}
