import { createContext } from 'react'

export const LangCtx = createContext({ t: k => k, lang: 'en', setLang: () => {} })

export const LABELS = {
  en: {
    appTitle: 'SPOREUS ATHLETE CONSOLE',
    appSub: 'BLOOMBERG TERMINAL FOR ENDURANCE ATHLETES',
    t_dashboard: 'DASHBOARD', t_zones: 'ZONE CALC', t_tests: 'PROTOCOLS',
    t_log: 'TRAINING LOG', t_macro: 'MACRO PLAN', t_glossary: 'GLOSSARY',
    t_recovery: 'RECOVERY', t_profile: 'PROFILE',
    readiness: 'READINESS STATUS', fresh: 'FRESH', trained: 'TRAINED', fatigued: 'FATIGUED',
    sessions: 'SESSIONS', volume: 'VOLUME', avgRpe: 'AVG RPE', tss7: '7-DAY TSS',
    recentSessions: 'RECENT SESSIONS', noSessions: 'No sessions logged yet. Use the Training Log tab.',
    quickLinks: 'QUICK LINKS',
    tssChartTitle: 'TRAINING LOAD \u2014 30 DAYS',
    ctlLabel: 'CTL (Fitness)', atlLabel: 'ATL (Fatigue)', tsbLabel: 'FORM (TSB)',
    noDataChart: 'Log sessions to see your training load trend.',
    zoneCalcTitle: 'ZONE CALCULATOR', hrMode: 'HEART RATE', pwrMode: 'POWER (W)', paceMode: 'RUN PACE',
    maxHRIn: 'MAX HEART RATE (bpm)', ageIn: 'AGE (Tanaka formula)', ftpIn: 'FTP (watts)',
    threshPaceIn: 'THRESHOLD PACE (MM:SS /km)',
    calcZonesBtn: 'CALCULATE ZONES', estMaxHR: 'Est. Max HR:',
    racePredTitle: 'RACE PREDICTOR (RIEGEL FORMULA)',
    raceDistLabel: 'RECENT RACE DISTANCE', raceTimeLabel: 'FINISH TIME (mm:ss or hh:mm:ss)',
    predictBtn: 'PREDICT TIMES', predsTitle: 'PREDICTIONS',
    distCol: 'DISTANCE', timeCol: 'TIME', paceCol: 'PACE /km',
    selectProto: 'SELECT PROTOCOL', calcBtn: 'CALCULATE', viewBtn: 'VIEW PROTOCOL',
    logTitle: 'LOG SESSION', dateL: 'DATE', typeL: 'SESSION TYPE',
    durL: 'DURATION (min)', rpeL: 'RPE (1\u201310)', notesL: 'NOTES (optional)',
    addBtn: '+ ADD SESSION', previewTSSBtn: 'PREVIEW TSS',
    sessionHistTitle: 'SESSION HISTORY', noSessionsYet: 'No sessions logged yet.',
    exportCSVBtn: 'EXPORT CSV',
    macroCycleTitle: '13-WEEK MACROCYCLE PLANNER', raceDateL: 'TARGET RACE DATE',
    weekHoursL: 'CURRENT WEEKLY HOURS', startDateLbl: 'Start date:',
    zoneLegendTitle: 'ZONE DISTRIBUTION LEGEND', weekBreakTitle: 'WEEKLY BREAKDOWN',
    glossTitle: 'SPORTS SCIENCE GLOSSARY', searchPlaceholder: 'Search terms\u2026',
    loadingTerms: 'Loading from sporeus.com\u2026',
    apiTermsLabel: 'Live from sporeus.com', localTermsLabel: 'Local terms',
    readMoreLink: 'Read more on sporeus.com \u2192',
    wellnessTitle: 'DAILY WELLNESS CHECK', sleepQL: 'SLEEP QUALITY',
    sorenessL: 'MUSCLE SORENESS', energyL: 'ENERGY LEVEL', moodL: 'MOOD', stressL: 'STRESS',
    readScoreTitle: 'READINESS SCORE',
    goLabel: 'GO', monitorLabel: 'MONITOR', restLabel: 'REST',
    saveEntryBtn: 'SAVE', hist7Title: '7-DAY HISTORY',
    alreadyLoggedMsg: 'Today\u2019s entry saved. Update below.',
    profileTitle: 'ATHLETE PROFILE', saveProfileBtn: 'SAVE PROFILE', savedMsg: '\u2713 SAVED',
    shareBtn: 'SHARE PROFILE', copiedMsg: '\u2713 COPIED',
    aboutTitle: 'ABOUT SPOREUS ATHLETE CONSOLE', installTitle: 'INSTALL AS APP',
    nameL: 'NAME', ageL: 'AGE', weightL: 'WEIGHT (kg)', sportL: 'PRIMARY SPORT',
    ftpL: 'FTP (watts)', vo2L: 'VO\u2082max (mL/kg/min)', threshPaceL: 'THRESHOLD PACE (/km)',
    goalL: 'SEASON GOAL',
    t_plan: '⚡ PLAN', planGoalL: 'TRAINING GOAL', planWeeksL: 'WEEKS TO RACE', planHoursL: 'WEEKLY HOURS',
    planLevelL: 'FITNESS LEVEL', genPlanBtn: 'GENERATE PLAN', logThisBtn: 'LOG SESSION',
    weekLabel: 'WEEK', phaseLabel: 'PHASE', tssEstLabel: 'EST. TSS', totalHrsLabel: 'TOTAL HRS',
    planSaved: 'Plan saved to log.', noPlanYet: 'Set your goal and generate a plan.',
    coachNote: 'Science-based periodization (Seiler, Issurin, Bompa). For personalized coaching:',
    bodyCompTitle: 'BODY COMPOSITION', navyMethodNote: 'U.S. Navy circumference method',
    neckL: 'NECK (cm)', waistL: 'WAIST (cm)', hipL: 'HIP (cm, women)', heightCmL: 'HEIGHT (cm)',
    genderL: 'GENDER', calcCompBtn: 'CALCULATE', bfPctL: 'BODY FAT', leanMassL: 'LEAN MASS',
    fatMassL: 'FAT MASS', bmiLbl: 'BMI',
    nutritionTitle: 'NUTRITION ESTIMATOR', activityL: 'ACTIVITY LEVEL',
    bmrL: 'BMR', tdeeL: 'TDEE', proteinL: 'PROTEIN TARGET', carbL: 'CARB TARGET',
    raceFuelTitle: 'RACE DAY FUELING', carbLoadL: 'Carb loading (48h before)', duringRaceL: 'During race',
  },
  tr: {
    appTitle: 'SPOREUS SPORCU KONSOLU',
    appSub: 'DAYANIKLILIK SPORCULARI \u0130\u00c7\u0130N BLOOMBERG TERM\u0130NAL',
    t_dashboard: 'PANO', t_zones: 'ZON HESAP', t_tests: 'PROTOKOLLER',
    t_log: 'ANTRENMAN LOG', t_macro: 'MAKRO PLAN', t_glossary: 'S\u00d6ZL\u00dcK',
    t_recovery: 'TOPARLANMA', t_profile: 'PROF\u0130L',
    readiness: 'HAZIRLIK DURUMU', fresh: 'D\u0130NLENM\u0130\u015e', trained: 'ANTRENMANLI', fatigued: 'YORGUN',
    sessions: 'ANTRENMAN', volume: 'HAC\u0130M', avgRpe: 'ORT. ZY', tss7: '7 G\u00dcNL\u00dcK TSS',
    recentSessions: 'SON ANTRENMANLAR',
    noSessions: 'Hen\u00fcz antrenman kaydedilmedi. Antrenman Log sekmesini kullan\u0131n.',
    quickLinks: 'HIZLI BA\u011eLANTILAR',
    tssChartTitle: 'ANTRENMAN Y\u00dcK\u00dc \u2014 30 G\u00dcN',
    ctlLabel: 'KTY (Kondisyon)', atlLabel: 'ATY (Yorgunluk)', tsbLabel: 'FORM (TSB)',
    noDataChart: 'Antrenman y\u00fck\u00fc trendini g\u00f6rmek i\u00e7in seans kaydedin.',
    zoneCalcTitle: 'ZON HESAPLAYICI', hrMode: 'KALP ATI\u015eI', pwrMode: 'G\u00dc\u00c7 (W)', paceMode: 'KO\u015eU TEMPOSU',
    maxHRIn: 'MAKS. KALP ATI\u015eI (at\u0131m/dak)', ageIn: 'YA\u015e (Tanaka form\u00fcl\u00fc)', ftpIn: 'FTP (watt)',
    threshPaceIn: 'E\u015e\u0130K TEMPOSU (DD:SS /km)',
    calcZonesBtn: 'ZONLARI HESAPLA', estMaxHR: 'Tahmini Maks HR:',
    racePredTitle: 'YARI\u015e TAHM\u0130NC\u0130S\u0130 (RIEGEL FORM\u00dcL\u00dc)',
    raceDistLabel: 'SON YARI\u015e MESAFES\u0130', raceTimeLabel: 'B\u0130T\u0130\u015e S\u00dcRES\u0130 (dd:ss veya ss:dd:ss)',
    predictBtn: 'TAHM\u0130N ET', predsTitle: 'TAHM\u0130NLER',
    distCol: 'MESAFE', timeCol: 'S\u00dcRE', paceCol: 'TEMPO /km',
    selectProto: 'PROTOKOL SE\u00c7', calcBtn: 'HESAPLA', viewBtn: 'PROTOKOL\u00dc G\u00d6R',
    logTitle: 'ANTRENMAN KAYDET', dateL: 'TAR\u0130H', typeL: 'ANTRENMAN T\u00dcR\u00dc',
    durL: 'S\u00dcRE (dak)', rpeL: 'ZY (1\u201310)', notesL: 'NOT (opsiyonel)',
    addBtn: '+ EKLE', previewTSSBtn: 'TSS \u00d6N\u0130ZLEME',
    sessionHistTitle: 'ANTRENMAN GE\u00c7M\u0130\u015e\u0130', noSessionsYet: 'Hen\u00fcz antrenman kayd\u0131 yok.',
    exportCSVBtn: 'CSV \u0130ND\u0130R',
    macroCycleTitle: '13 HAFTALIK MAKRO PLAN', raceDateL: 'HEDEF YARI\u015e TAR\u0130H\u0130',
    weekHoursL: 'HAFTALIK MEVCUT SAAT', startDateLbl: 'Ba\u015flang\u0131\u00e7 tarihi:',
    zoneLegendTitle: 'ZON DA\u011eILIMI A\u00c7IKLAMASI', weekBreakTitle: 'HAFTALIK D\u00d6K\u00dcM',
    glossTitle: 'SPOR B\u0130L\u0130M\u0130 S\u00d6ZL\u00dc\u011e\u00dc', searchPlaceholder: 'Terim ara\u2026',
    loadingTerms: 'sporeus.com\u2019dan y\u00fckleniyor\u2026',
    apiTermsLabel: 'sporeus.com\u2019dan canl\u0131', localTermsLabel: 'Yerel terimler',
    readMoreLink: 'sporeus.com\u2019da devam\u0131n\u0131 oku \u2192',
    wellnessTitle: 'G\u00dcNL\u00dcK SA\u011eLIK KONTROL\u00dc', sleepQL: 'UYKU KAL\u0130TES\u0130',
    sorenessL: 'KAS A\u011eRISI', energyL: 'ENERJ\u0130 SEV\u0130YES\u0130', moodL: 'RUH HAL\u0130', stressL: 'STRES',
    readScoreTitle: 'HAZIRLIK SKORU',
    goLabel: 'G\u0130T', monitorLabel: '\u0130ZLE', restLabel: 'D\u0130NLEN',
    saveEntryBtn: 'KAYDET', hist7Title: '7 G\u00dcNL\u00dcK GE\u00c7M\u0130\u015e',
    alreadyLoggedMsg: 'Bug\u00fcnk\u00fc giri\u015f kaydedildi. G\u00fcncellemek i\u00e7in a\u015fa\u011f\u0131y\u0131 kullan\u0131n.',
    profileTitle: 'SPORCU PROF\u0130L\u0130', saveProfileBtn: 'PROF\u0130L\u0130 KAYDET', savedMsg: '\u2713 KAYDED\u0130LD\u0130',
    shareBtn: 'PROF\u0130L\u0130 PAYLA\u015e', copiedMsg: '\u2713 KOPYALANDI',
    aboutTitle: 'UYGULAMA HAKKINDA', installTitle: 'UYGULAMA OLARAK Y\u00dcKLE',
    nameL: 'AD SOYAD', ageL: 'YA\u015e', weightL: 'K\u0130LO (kg)', sportL: 'ANA SPOR',
    ftpL: 'FTP (watt)', vo2L: 'VO\u2082maks (mL/kg/dak)', threshPaceL: 'E\u015e\u0130K TEMPOSU (/km)',
    goalL: 'SEZON HEDEFİ',
    t_plan: '⚡ PLAN', planGoalL: 'ANTRENMAN HEDEFİ', planWeeksL: 'YARIŞA HAFTA', planHoursL: 'HAFTALIK SAAT',
    planLevelL: 'KONDİSYON DÜZEYİ', genPlanBtn: 'PLAN OLUŞTUR', logThisBtn: 'KAYDET',
    weekLabel: 'HAFTA', phaseLabel: 'FAZ', tssEstLabel: 'TAHMİNİ TSS', totalHrsLabel: 'TOPLAM SAAT',
    planSaved: 'Plan kaydedildi.', noPlanYet: 'Hedefinizi seçin ve plan oluşturun.',
    coachNote: 'Bilim tabanlı periyodizasyon (Seiler, Issurin, Bompa). Kişisel antrenör için:',
    bodyCompTitle: 'VÜCUT KOMPOZİSYONU', navyMethodNote: 'ABD Donanması çevre ölçüm yöntemi',
    neckL: 'BOYUN (cm)', waistL: 'BEL (cm)', hipL: 'KALÇA (cm, kadın)', heightCmL: 'BOY (cm)',
    genderL: 'CİNSİYET', calcCompBtn: 'HESAPLA', bfPctL: 'YAĞ ORANI', leanMassL: 'YAGSIZ KÜTLE',
    fatMassL: 'YAĞ KÜTLESİ', bmiLbl: 'BKİ',
    nutritionTitle: 'BESLENME HESAPLAYICI', activityL: 'AKTİVİTE DÜZEYİ',
    bmrL: 'BMH', tdeeL: 'GTGE', proteinL: 'PROTEİN HEDEFİ', carbL: 'KARBONHİDRAT HEDEFİ',
    raceFuelTitle: 'YARIŞ GÜNÜ YAKITI', carbLoadL: 'Karbonhidrat yüklemesi (48s önce)', duringRaceL: 'Yarış sırasında',
  }
}

// ─── Tabs ──────────────────────────────────────────────────────────────────────
export const TABS = [
  { id: 'dashboard',     icon: '\u25c8', lk: 't_dashboard' },
  { id: 'zones',         icon: '\u25c9', lk: 't_zones' },
  { id: 'tests',         icon: '\u25b2', lk: 't_tests' },
  { id: 'log',           icon: '\u2261', lk: 't_log' },
  { id: 'periodization', icon: '\u229e', lk: 't_macro' },
  { id: 'plan',          icon: '\u26a1', lk: 't_plan' },
  { id: 'glossary',      icon: '\u25c7', lk: 't_glossary' },
  { id: 'recovery',      icon: '\u2661', lk: 't_recovery' },
  { id: 'profile',       icon: '\u25cb', lk: 't_profile' },
]
