import { createContext } from 'react'

export const LangCtx = createContext({ t: k => k, lang: 'en', setLang: () => {} })

export const LABELS = {
  en: {
    appTitle: 'SPOREUS ATHLETE CONSOLE',
    appSub: 'BLOOMBERG TERMINAL FOR ENDURANCE ATHLETES',
    t_dashboard: 'DASHBOARD', t_zones: 'ZONE CALC', t_tests: 'PROTOCOLS',
    t_log: 'TRAINING LOG', t_macro: 'MACRO PLAN', t_glossary: 'GLOSSARY',
    t_recovery: 'RECOVERY', t_profile: 'PROFILE', t_sport: 'SPORT PLAN',
    readiness: 'READINESS STATUS', fresh: 'FRESH', trained: 'TRAINED', fatigued: 'FATIGUED',
    sessions: 'SESSIONS', volume: 'VOLUME', avgRpe: 'AVG RPE', tss7: '7-DAY TSS',
    recentSessions: 'RECENT SESSIONS', noSessions: 'No sessions logged yet. Use the Training Log tab.',
    quickLinks: 'QUICK LINKS',
    tssChartTitle: 'TRAINING LOAD \u2014 30 DAYS',
    ctlLabel: 'CTL (Fitness)', atlLabel: 'ATL (Fatigue)', tsbLabel: 'FORM (TSB)',
    noDataChart: 'Log sessions to see your training load trend.',
    zoneCalcTitle: 'ZONE CALCULATOR', hrMode: 'HEART RATE', pwrMode: 'POWER (W)', paceMode: 'RUN PACE',
    maxHRIn: 'MAX HEART RATE (bpm)', ageIn: 'AGE (Tanaka formula)', ftpIn: 'FTP (watts)',
    threshPaceIn: 'THRESHOLD PACE (MM:SS /km)',
    calcZonesBtn: 'CALCULATE ZONES', estMaxHR: 'Est. Max HR:',
    racePredTitle: 'RACE PREDICTOR (RIEGEL FORMULA)',
    raceDistLabel: 'RECENT RACE DISTANCE', raceTimeLabel: 'FINISH TIME (mm:ss or hh:mm:ss)',
    predictBtn: 'PREDICT TIMES', predsTitle: 'PREDICTIONS',
    distCol: 'DISTANCE', timeCol: 'TIME', paceCol: 'PACE /km',
    selectProto: 'SELECT PROTOCOL', calcBtn: 'CALCULATE', viewBtn: 'VIEW PROTOCOL',
    logTitle: 'LOG SESSION', dateL: 'DATE', typeL: 'SESSION TYPE',
    durL: 'DURATION (min)', rpeL: 'RPE (1\u201310)', notesL: 'NOTES (optional)',
    addBtn: '+ ADD SESSION', previewTSSBtn: 'PREVIEW TSS',
    sessionHistTitle: 'SESSION HISTORY', noSessionsYet: 'No sessions logged yet.',
    exportCSVBtn: 'EXPORT CSV',
    macroCycleTitle: '13-WEEK MACROCYCLE PLANNER', raceDateL: 'TARGET RACE DATE',
    weekHoursL: 'CURRENT WEEKLY HOURS', startDateLbl: 'Start date:',
    zoneLegendTitle: 'ZONE DISTRIBUTION LEGEND', weekBreakTitle: 'WEEKLY BREAKDOWN',
    glossTitle: 'SPORTS SCIENCE GLOSSARY', searchPlaceholder: 'Search terms\u2026',
    loadingTerms: 'Loading from sporeus.com\u2026',
    apiTermsLabel: 'Live from sporeus.com', localTermsLabel: 'Local terms',
    readMoreLink: 'Read more on sporeus.com \u2192',
    wellnessTitle: 'DAILY WELLNESS CHECK', sleepQL: 'SLEEP QUALITY',
    sorenessL: 'MUSCLE SORENESS', energyL: 'ENERGY LEVEL', moodL: 'MOOD', stressL: 'STRESS',
    readScoreTitle: 'READINESS SCORE',
    goLabel: 'GO', monitorLabel: 'MONITOR', restLabel: 'REST',
    saveEntryBtn: 'SAVE', hist7Title: '7-DAY HISTORY',
    alreadyLoggedMsg: 'Today\u2019s entry saved. Update below.',
    profileTitle: 'ATHLETE PROFILE', saveProfileBtn: 'SAVE PROFILE', savedMsg: '\u2713 SAVED',
    shareBtn: 'SHARE PROFILE', copiedMsg: '\u2713 COPIED',
    aboutTitle: 'ABOUT SPOREUS ATHLETE CONSOLE', installTitle: 'INSTALL AS APP',
    nameL: 'NAME', ageL: 'AGE', weightL: 'WEIGHT (kg)', sportL: 'PRIMARY SPORT',
    ftpL: 'FTP (watts)', vo2L: 'VO\u2082max (mL/kg/min)', threshPaceL: 'THRESHOLD PACE (/km)',
    goalL: 'SEASON GOAL',
    t_plan: '⚡ PLAN', planGoalL: 'TRAINING GOAL', planWeeksL: 'WEEKS TO RACE', planHoursL: 'WEEKLY HOURS',
    planLevelL: 'FITNESS LEVEL', genPlanBtn: 'GENERATE PLAN', logThisBtn: 'LOG SESSION',
    weekLabel: 'WEEK', phaseLabel: 'PHASE', tssEstLabel: 'EST. TSS', totalHrsLabel: 'TOTAL HRS',
    planSaved: 'Plan saved to log.', noPlanYet: 'Set your goal and generate a plan.',
    coachNote: 'Science-based periodization (Seiler, Issurin, Bompa). For personalized coaching:',
    bodyCompTitle: 'BODY COMPOSITION', navyMethodNote: 'U.S. Navy circumference method',
    neckL: 'NECK (cm)', waistL: 'WAIST (cm)', hipL: 'HIP (cm, women)', heightCmL: 'HEIGHT (cm)',
    genderL: 'GENDER', calcCompBtn: 'CALCULATE', bfPctL: 'BODY FAT', leanMassL: 'LEAN MASS',
    fatMassL: 'FAT MASS', bmiLbl: 'BMI',
    nutritionTitle: 'NUTRITION ESTIMATOR', activityL: 'ACTIVITY LEVEL',
    bmrL: 'BMR', tdeeL: 'TDEE', proteinL: 'PROTEIN TARGET', carbL: 'CARB TARGET',
    raceFuelTitle: 'RACE DAY FUELING', carbLoadL: 'Carb loading (48h before)', duringRaceL: 'During race',
    sleepHrsL: 'SLEEP HOURS', bedtimeL: 'BEDTIME', wakeL: 'WAKE TIME', sleepAutoNote: 'Auto from bed/wake',
    sleepTrendTitle: 'SLEEP TREND (7 DAYS)', sleepLowWarning: 'Low readiness may be linked to insufficient sleep (<7h avg)',
    acwrTitle: 'WORKLOAD RATIO (ACWR)', acwrAcute: 'ACUTE (7d)', acwrChronic: 'CHRONIC (28d)',
    acwrUnder: 'Undertrained — room to increase load', acwrSweet: 'Sweet Spot — optimal training zone',
    acwrCaution: 'Caution — elevated injury risk', acwrDanger: 'Danger Zone — reduce load immediately',
    acwrOptimal: 'OPTIMAL', acwrInsufficient: 'INSUFFICIENT DATA',
    acwrRec: 'Tomorrow suggestion', acwrNote: 'Hulin et al. (2016) acute:chronic workload ratio',
    pacingTitle: 'RACE PACING PLAN', pacingDistL: 'RACE DISTANCE', pacingTimeL: 'TARGET TIME (hh:mm:ss)',
    pacingStratL: 'STRATEGY', pacingGenBtn: 'GENERATE PLAN', pacingCopyBtn: 'COPY PLAN',
    pacingPrintBtn: 'PRINT', pacingKm: 'KM', pacingSplit: 'SPLIT', pacingCumul: 'CUMUL.',
    pacingFuel: 'FUELING', pacingNegSplit: 'Negative Split', pacingEvenSplit: 'Even Split',
    pacingPosSplit: 'Positive Split',
    weightTitle: 'WEIGHT & HYDRATION', morningWtL: 'MORNING WEIGHT (kg)', weightSaveBtn: 'LOG WEIGHT',
    weightTrend: '30-DAY WEIGHT TREND', weight7avg: '7-day avg', weightDehydWarn: 'Possible dehydration — increase fluid intake',
    sweatTitle: 'SWEAT RATE CALCULATOR', sweatPre: 'PRE-WEIGHT (kg)', sweatPost: 'POST-WEIGHT (kg)',
    sweatFluid: 'FLUID INTAKE (ml)', sweatDur: 'DURATION (min)', sweatCalcBtn: 'CALCULATE',
    sweatResult: 'Your sweat rate', sweatReplace: 'replace 80% during exercise',
    raceWeightTitle: 'RACE WEIGHT TARGET', raceWeightTarget: 'TARGET WEIGHT (kg)', raceWeeksTil: 'WEEKS UNTIL RACE',
    raceWeightSafe: 'Safe weekly loss', raceWeightOk: 'Achievable', raceWeightAggressive: 'Too aggressive — risk muscle loss',
    primarySportL: 'PRIMARY SPORT', athleteLevelL: 'ATHLETE LEVEL',
    triathlonTypeL: 'TRIATHLON DISTANCE', secondarySportsL: 'SECONDARY SPORTS',
    coachCardTitle: 'COACHING — HÜSEYIN AKBULUT', connectCoachBtn: 'BECOME AN ATHLETE',
    connectedCoachMsg: '◈ CONNECTED TO COACH', sendDataCoachBtn: 'SEND DATA TO COACH',
    coachConnectNote: 'Download your training data file and send it to your coach for analysis.',
    disconnectCoachBtn: 'DISCONNECT',
    // v4.3 intelligence
    insightsTitle: 'TRAINING INSIGHTS', injuryRiskTitle: 'INJURY RISK ASSESSMENT',
    sessionQualityTitle: 'SESSION QUALITY', smartAdjTitle: 'SMART ADJUSTMENTS',
    athleteIntelTitle: 'ATHLETE INTELLIGENCE', copyAnalysisBtn: 'Copy Full Analysis',
    loadTrendLabel: 'LOAD TREND', zoneBalanceLabel: 'ZONE BALANCE',
    fitnessLabel: 'FITNESS PROJECTION', recovCorrLabel: 'LOAD↔RECOVERY',
    // v4.4 storytelling
    weekStoryTitle: 'THIS WEEK\'S STORY', didYouKnowTitle: 'DID YOU KNOW?',
    milestoneTitle: 'MILESTONE UNLOCKED!', trainingAgeTitle: 'TRAINING AGE',
    nextNoteBtn: 'Next fact →', shareStoryBtn: '⤴ Share', copyStoryBtn: '⎘ Copy',
    trainingAgeLabel: 'Training age', ctlScaleLabel: 'FITNESS SCALE',
    // v5.14 Today View
    t_today: 'TODAY',
    todaySession: "TODAY'S SESSION", todayRest: 'REST DAY', todayDone: 'DONE',
    todayMarkDone: 'MARK DONE', todayLogThis: 'LOG THIS',
    todayNoPlan: 'No plan active — generate one in the PLAN tab.',
    todayReadiness: "TODAY'S READINESS", todaySaveReadiness: 'SAVE READINESS',
    todaySaved: 'SAVED', todayQuickStats: 'QUICK STATS',
    todayYesterday: 'YESTERDAY', todayThisWeek: 'THIS WEEK', todayConsec: 'CONSEC.',
    todaySuggestion: 'SMART SUGGESTION', todayLogYesterday: '+ Log Yesterday',
    // TodayView — coach badge + rings + share (STRUCTURE-S5)
    todayCoachMsg: 'unread message from your coach', todayCoachMsgs: 'unread messages from your coach',
    todayDismiss: 'DISMISS',
    shareProgress: 'Share Progress →',
    weeklyRings: 'WEEKLY RINGS', weekTSS: 'WEEK TSS', wellness: 'WELLNESS',
    // CoachSquadView (STRUCTURE-S5)
    squadTitle: 'SQUAD', loadingSquad: 'Loading squad…',
    connected: 'CONNECTED',
    inviteLink: '+ INVITE LINK',
    rtLive: 'Live', rtReconnecting: 'Reconnecting…',
    demoDataWarning: 'DEMO DATA — connect real athletes to see live metrics',
    noAthletesYet: 'No athletes connected yet. Share this invite code:',
    weeklyDigest: '◈ WEEKLY DIGEST',
    copyAll: 'COPY ALL', copied: '✓ COPIED',
    squadColAthlete: 'ATHLETE', squadColReadiness: 'READINESS',
    squadColTSB: 'TSB', squadColACWR: 'ACWR',
    squadColAdherence: 'ADHERENCE', squadColStatus: 'STATUS',
    squadColFlag: 'FLAG', squadColMsg: 'MSG', squadColCompare: 'CMP',
    weeklyRecapDismiss: '[dismiss]', weeklyRecapLabel: 'WK',
    // Team Announcements
    teamAnnTitle: 'TEAM ANNOUNCEMENTS', teamAnnPost: 'Post', teamAnnPlaceholder: 'Write an announcement to your squad… (max 280 chars)',
    teamAnnMarkAllRead: 'Mark all read', teamAnnUnread: 'unread', teamAnnNone: 'No announcements yet.',
    teamAnnNoneAthlete: 'No announcements from your coach yet.',
    // Quick-Add Session
    quickAddTitle: 'QUICK LOG SESSION', quickAddSport: 'SPORT', quickAddDuration: 'DURATION (min)',
    quickAddRpe: 'RPE (1–10)', quickAddNotes: 'NOTES (optional)', quickAddSave: '+ LOG',
    quickAddCancel: 'Cancel', quickAddEstTss: 'Est. TSS',
    // Keyboard shortcuts
    shortcutsTitle: 'KEYBOARD SHORTCUTS', shortcutsClose: 'Close',
    shortcutsNav: 'Navigation', shortcutsActions: 'Actions',
    // Weekly digest notification
    weeklyDigestNotifTitle: 'Weekly Summary',
    // Reports tab (v7.47)
    t_reports: 'REPORTS',
    reportsTitle: 'PDF REPORTS', reportsGenerate: 'Generate', reportsLocked: 'Locked',
    reportsGenerating: 'Generating…', reportsHistory: 'Report History',
    reportsNoHistory: 'No reports generated yet.',
    reportsDownload: 'Download', reportsDelete: 'Delete', reportsExpired: 'Expired',
    // Sport Program Builder (C6)
    spb_sport_rowing: 'Rowing', spb_sport_running: 'Running', spb_sport_cycling: 'Cycling',
    spb_sport_swimming: 'Swimming', spb_sport_triathlon: 'Triathlon',
    spb_goal_base: 'Build Base Fitness', spb_goal_race: 'Race Preparation',
    spb_goal_peak: 'Peak for Event', spb_goal_maintain: 'Maintain Current Level',
    spb_title: 'SPORT PROGRAM BUILDER',
    spb_sub: 'Monte Carlo optimizer · Banister impulse-response · 500 simulations',
    spb_step1Title: 'SPORT & GOAL', spb_selectSport: 'SELECT SPORT', spb_primaryGoal: 'PRIMARY GOAL',
    spb_raceDate: 'RACE DATE (optional)', spb_daysToRace: 'days to race',
    spb_preFilledProfile: '✓ Pre-filled from your profile',
    spb_step2Title: 'PERFORMANCE BASELINE',
    spb_fromTestLog: '✓ From your test log', spb_fromLog: '✓ From your log',
    spb_fromTrainingData: '✓ From your training data', spb_fromLastWeeks: '✓ From last 4 weeks',
    spb_step3Title: 'TRAINING CONSTRAINTS',
    spb_planDuration: 'Plan Duration (weeks)', spb_currentTSSLabel: 'Current Weekly TSS',
    spb_peakTSSLabel: 'Peak Weekly TSS Target', spb_currentCTL: 'Current CTL (fitness)',
    spb_currentATL: 'Current ATL (fatigue)', spb_sessionsPerWeek: 'Sessions/week (avg)',
    spb_recoveryAuto: 'Recovery weeks auto-inserted every 4th week.',
    spb_step4Title: 'GENERATE PLAN',
    spb_monteCarloSub: '500 Monte Carlo simulations to find highest-scoring plan.',
    spb_simulating: 'SIMULATING\u2026', spb_runOptimizer: '\u26a1 RUN OPTIMIZER',
    spb_btnNext: 'NEXT \u2192', spb_btnBack: '\u2190 BACK', spb_generatePlan: 'GENERATE PLAN \u2192',
    spb_step5Title: 'YOUR OPTIMIZED PLAN',
    spb_daysToRaceLabel: 'DAYS TO RACE', spb_planScore: 'PLAN SCORE', spb_avgScore: 'AVG SCORE',
    spb_peakForm: 'PEAK FORM', spb_peakTSBLabel: 'PEAK TSB',
    spb_scoreDistTitle: 'SCORE DISTRIBUTION (500 simulations)',
    spb_weeklyPlanTitle: 'WEEKLY PLAN \u2014 PLAN vs ACTUAL',
    spb_exportCSV: '\u2193 CSV', spb_saved: '\u2713 SAVED', spb_saveToLog: '+ SAVE TO LOG',
    spb_adaptPlan: '\u26a1 ADAPT PLAN', spb_resetPlan: '\u2715 reset',
    spb_colWk: 'WK', spb_colPlanned: 'PLANNED', spb_colActual: 'ACTUAL',
    spb_colVariance: 'VARIANCE', spb_colSessions: 'SESSIONS', spb_colDetail: 'DETAIL',
    spb_consecutiveWeeks: 'consecutive weeks within plan',
    spb_fitnessTrace: 'FITNESS / FATIGUE TRACE (Banister)',
    spb_ctlLegend: '\u2014 CTL (Fitness)', spb_atlLegend: '\u2014 ATL (Fatigue)',
    spb_peakFormLegend: '| Peak form day',
    spb_comparePlans: '\u21c4 Compare top 2 plans',
    spb_simulateMissed: 'SIMULATE MISSED WEEK', spb_missedSelectWeek: 'Select week\u2026',
    spb_missWeekBtn: 'Miss this week', spb_missedImpact: 'TSB drops',
    spb_peakFormShifts: 'peak form shifts', spb_daysLater: 'days later', spb_daysEarlier: 'days earlier',
    spb_buildNewPlan: 'BUILD NEW PLAN',
    spb_modalPrint: '\u2399 PRINT', spb_modalSessions: 'PLANNED SESSIONS',
    spb_modalTrace: 'DAILY BANISTER TRACE', spb_modalDay: 'DAY',
    // Status banner (C5)
    status_outage: null, status_outage_suffix: 'is experiencing an outage',
    status_degraded: null, status_degraded_suffix: 'is degraded \u2014 some features may be slow',
    status_check_stale: 'status check may be stale',
    // Semantic search (C7)
    ssPlaceholder: "Search sessions by meaning\u2026 (e.g. 'hard interval week')",
    ssSearching: 'searching\u2026',
    ssUpgradeMsg: 'Semantic search requires a Coach or Club plan.',
    ssUpgradeLink: 'Upgrade',
    ssRetry: 'Retry',
    ssNoResults: 'No matching sessions found. Try a different phrase or add more session notes.',
    ssMinChars: 'Type at least 3 characters to search.',
    ssIdleTitle: 'Search your sessions by meaning, not just keywords.',
    ssIdleCorpus: 'Sessions are indexed as you log them. New accounts build their corpus over the first week.',
    ssNavHint: '\u2191\u2193 navigate', ssJumpHint: '\u21b5 jump to session', ssEscHint: 'Esc close',
    ssExample1: 'hard interval week before the race',
    ssExample2: 'easy recovery run with low HR',
    ssExample3: 'long ride in the mountains',
    ssExample4: 'felt exhausted, poor sleep',
    // Global FTS search (P7)
    gsTitle: 'Search Everything',
    gsPlaceholder: 'Search sessions, notes, messages\u2026',
    gsSearching: 'searching\u2026',
    gsSemantic: 'semantic \u2192',
    gsRecent: 'Recent',
    gsNoResults: 'No results. Try a different word or phrase.',
    gsKind_session: 'Sessions',
    gsKind_note: 'Notes',
    gsKind_message: 'Messages',
    gsKind_announcement: 'Announcements',
    gsKind_athlete: 'Athletes',
    // Live squad feed (C7)
    feedSquadLabel: 'SQUAD FEED',
    feedNoAthletes: 'No athletes yet \u2014 invite your first athlete from the Squad tab.',
    feedNoActivity: 'No activity yet \u2014 waiting for squad updates\u2026',
    feedConnecting: 'Connecting to live feed\u2026',
    feedOnline: 'online',
    // E11 — session comments + presence
    commentsTitle: 'COMMENTS',
    commentPlaceholder: 'Add a comment\u2026 (max 2000 chars)',
    commentPost: 'POST',
    commentEdit: 'Edit',
    commentDelete: 'Delete',
    commentEdited: '(edited)',
    commentDeleted: '[deleted]',
    commentReply: 'Reply',
    commentCancel: 'Cancel',
    commentSave: 'Save',
    commentEmpty: 'No comments yet.',
    commentOffline: 'Comment queued \u2014 will send when online.',
    coachPresenceViewing: 'Viewing now',
    coachPresenceNever: 'Not yet viewed',
    coachPresenceLabel: 'COACH',
    coachPresenceAthlete: 'ATHLETE',
  },
  tr: {
    appTitle: 'SPOREUS SPORCU KONSOLU',
    appSub: 'DAYANIKLILIK SPORCULARI \u0130\u00c7\u0130N BLOOMBERG TERM\u0130NAL',
    t_dashboard: 'PANO', t_zones: 'ZON HESAP', t_tests: 'PROTOKOLLER',
    t_log: 'ANTRENMAN LOG', t_macro: 'MAKRO PLAN', t_glossary: 'S\u00d6ZL\u00dcK',
    t_recovery: 'TOPARLANMA', t_profile: 'PROFİL', t_sport: 'SPOR PLAN',
    readiness: 'HAZIRLIK DURUMU', fresh: 'D\u0130NLENM\u0130\u015e', trained: 'ANTRENMANLI', fatigued: 'YORGUN',
    sessions: 'ANTRENMAN', volume: 'HAC\u0130M', avgRpe: 'ORT. ZY', tss7: '7 G\u00dcNL\u00dcK TSS',
    recentSessions: 'SON ANTRENMANLAR',
    noSessions: 'Hen\u00fcz antrenman kaydedilmedi. Antrenman Log sekmesini kullan\u0131n.',
    quickLinks: 'HIZLI BA\u011eLANTILAR',
    tssChartTitle: 'ANTRENMAN Y\u00dcK\u00dc \u2014 30 G\u00dcN',
    ctlLabel: 'KTY (Kondisyon)', atlLabel: 'ATY (Yorgunluk)', tsbLabel: 'FORM (TSB)',
    noDataChart: 'Antrenman y\u00fck\u00fc trendini g\u00f6rmek i\u00e7in seans kaydedin.',
    zoneCalcTitle: 'ZON HESAPLAYICI', hrMode: 'KALP ATI\u015eI', pwrMode: 'G\u00dc\u00c7 (W)', paceMode: 'KO\u015eU TEMPOSU',
    maxHRIn: 'MAKS. KALP ATI\u015eI (at\u0131m/dak)', ageIn: 'YA\u015e (Tanaka form\u00fcl\u00fc)', ftpIn: 'FTP (watt)',
    threshPaceIn: 'E\u015e\u0130K TEMPOSU (DD:SS /km)',
    calcZonesBtn: 'ZONLARI HESAPLA', estMaxHR: 'Tahmini Maks HR:',
    racePredTitle: 'YARI\u015e TAHM\u0130NC\u0130S\u0130 (RIEGEL FORM\u00dcL\u00dc)',
    raceDistLabel: 'SON YARI\u015e MESAFES\u0130', raceTimeLabel: 'B\u0130T\u0130\u015e S\u00dcRES\u0130 (dd:ss veya ss:dd:ss)',
    predictBtn: 'TAHM\u0130N ET', predsTitle: 'TAHM\u0130NLER',
    distCol: 'MESAFE', timeCol: 'S\u00dcRE', paceCol: 'TEMPO /km',
    selectProto: 'PROTOKOL SE\u00c7', calcBtn: 'HESAPLA', viewBtn: 'PROTOKOL\u00dc G\u00d6R',
    logTitle: 'ANTRENMAN KAYDET', dateL: 'TAR\u0130H', typeL: 'ANTRENMAN T\u00dcR\u00dc',
    durL: 'S\u00dcRE (dak)', rpeL: 'ZY (1\u201310)', notesL: 'NOT (opsiyonel)',
    addBtn: '+ EKLE', previewTSSBtn: 'TSS \u00d6N\u0130ZLEME',
    sessionHistTitle: 'ANTRENMAN GE\u00c7M\u0130\u015e\u0130', noSessionsYet: 'Hen\u00fcz antrenman kayd\u0131 yok.',
    exportCSVBtn: 'CSV \u0130ND\u0130R',
    macroCycleTitle: '13 HAFTALIK MAKRO PLAN', raceDateL: 'HEDEF YARI\u015e TAR\u0130H\u0130',
    weekHoursL: 'HAFTALIK MEVCUT SAAT', startDateLbl: 'Ba\u015flang\u0131\u00e7 tarihi:',
    zoneLegendTitle: 'ZON DA\u011eILIMI A\u00c7IKLAMASI', weekBreakTitle: 'HAFTALIK D\u00d6K\u00dcM',
    glossTitle: 'SPOR B\u0130L\u0130M\u0130 S\u00d6ZL\u00dc\u011e\u00dc', searchPlaceholder: 'Terim ara\u2026',
    loadingTerms: 'sporeus.com\u2019dan y\u00fckleniyor\u2026',
    apiTermsLabel: 'sporeus.com\u2019dan canl\u0131', localTermsLabel: 'Yerel terimler',
    readMoreLink: 'sporeus.com\u2019da devam\u0131n\u0131 oku \u2192',
    wellnessTitle: 'G\u00dcNL\u00dcK SA\u011eLIK KONTROL\u00dc', sleepQL: 'UYKU KAL\u0130TES\u0130',
    sorenessL: 'KAS A\u011eRISI', energyL: 'ENERJ\u0130 SEV\u0130YES\u0130', moodL: 'RUH HAL\u0130', stressL: 'STRES',
    readScoreTitle: 'HAZIRLIK SKORU',
    goLabel: 'G\u0130T', monitorLabel: '\u0130ZLE', restLabel: 'D\u0130NLEN',
    saveEntryBtn: 'KAYDET', hist7Title: '7 G\u00dcNL\u00dcK GE\u00c7M\u0130\u015e',
    alreadyLoggedMsg: 'Bug\u00fcnk\u00fc giri\u015f kaydedildi. G\u00fcncellemek i\u00e7in a\u015fa\u011f\u0131y\u0131 kullan\u0131n.',
    profileTitle: 'SPORCU PROF\u0130L\u0130', saveProfileBtn: 'PROF\u0130L\u0130 KAYDET', savedMsg: '\u2713 KAYDED\u0130LD\u0130',
    shareBtn: 'PROF\u0130L\u0130 PAYLA\u015e', copiedMsg: '\u2713 KOPYALANDI',
    aboutTitle: 'UYGULAMA HAKKINDA', installTitle: 'UYGULAMA OLARAK Y\u00dcKLE',
    nameL: 'AD SOYAD', ageL: 'YA\u015e', weightL: 'K\u0130LO (kg)', sportL: 'ANA SPOR',
    ftpL: 'FTP (watt)', vo2L: 'VO\u2082maks (mL/kg/dak)', threshPaceL: 'E\u015e\u0130K TEMPOSU (/km)',
    goalL: 'SEZON HEDEFİ',
    t_plan: '⚡ PLAN', planGoalL: 'ANTRENMAN HEDEFİ', planWeeksL: 'YARIŞA HAFTA', planHoursL: 'HAFTALIK SAAT',
    planLevelL: 'KONDİSYON DÜZEYİ', genPlanBtn: 'PLAN OLUŞTUR', logThisBtn: 'KAYDET',
    weekLabel: 'HAFTA', phaseLabel: 'FAZ', tssEstLabel: 'TAHMİNİ TSS', totalHrsLabel: 'TOPLAM SAAT',
    planSaved: 'Plan kaydedildi.', noPlanYet: 'Hedefinizi seçin ve plan oluşturun.',
    coachNote: 'Bilim tabanlı periyodizasyon (Seiler, Issurin, Bompa). Kişisel antrenör için:',
    bodyCompTitle: 'VÜCUT KOMPOZİSYONU', navyMethodNote: 'ABD Donanması çevre ölçüm yöntemi',
    neckL: 'BOYUN (cm)', waistL: 'BEL (cm)', hipL: 'KALÇA (cm, kadın)', heightCmL: 'BOY (cm)',
    genderL: 'CİNSİYET', calcCompBtn: 'HESAPLA', bfPctL: 'YAĞ ORANI', leanMassL: 'YAGSIZ KÜTLE',
    fatMassL: 'YAĞ KÜTLESİ', bmiLbl: 'BKİ',
    nutritionTitle: 'BESLENME HESAPLAYICI', activityL: 'AKTİVİTE DÜZEYİ',
    bmrL: 'BMH', tdeeL: 'GTGE', proteinL: 'PROTEİN HEDEFİ', carbL: 'KARBONHİDRAT HEDEFİ',
    raceFuelTitle: 'YARIŞ GÜNÜ YAKITI', carbLoadL: 'Karbonhidrat yüklemesi (48s önce)', duringRaceL: 'Yarış sırasında',
    sleepHrsL: 'UYKU SAATİ', bedtimeL: 'YATMA SAATİ', wakeL: 'UYANMA SAATİ', sleepAutoNote: 'Yatma/uyanma saatinden otomatik',
    sleepTrendTitle: 'UYKU TRENDİ (7 GÜN)', sleepLowWarning: 'Düşük hazırlık yetersiz uyku ile ilişkili olabilir (<7 saat ort.)',
    acwrTitle: 'İŞ YÜKÜ ORANI (ACWR)', acwrAcute: 'AKUT (7g)', acwrChronic: 'KRONİK (28g)',
    acwrUnder: 'Az antrenman — yük artırılabilir', acwrSweet: 'İdeal Bölge — optimal antrenman',
    acwrCaution: 'Dikkat — yaralanma riski artıyor', acwrDanger: 'Tehlike Bölgesi — yükü hemen azalt',
    acwrOptimal: 'OPTİMAL', acwrInsufficient: 'YETERSİZ VERİ',
    acwrRec: 'Yarın önerisi', acwrNote: 'Hulin ve ark. (2016) akut:kronik iş yükü oranı',
    pacingTitle: 'YARIŞ TEMPO PLANI', pacingDistL: 'YARIŞ MESAFESİ', pacingTimeL: 'HEDEF SÜRE (ss:dd:ss)',
    pacingStratL: 'STRATEJİ', pacingGenBtn: 'PLAN OLUŞTUR', pacingCopyBtn: 'PLANI KOPYALA',
    pacingPrintBtn: 'YAZDIR', pacingKm: 'KM', pacingSplit: 'BÖLÜM', pacingCumul: 'TOPLAM',
    pacingFuel: 'YAKITLAMA', pacingNegSplit: 'Negatif Split', pacingEvenSplit: 'Eşit Split',
    pacingPosSplit: 'Pozitif Split',
    weightTitle: 'KİLO & HİDRASYON', morningWtL: 'SABAH KILOSU (kg)', weightSaveBtn: 'KİLO KAYDET',
    weightTrend: '30 GÜNLÜK KİLO TRENDİ', weight7avg: '7 günlük ort.', weightDehydWarn: 'Olası dehidrasyon — sıvı alımını artır',
    sweatTitle: 'TER ORANI HESAPLAYICI', sweatPre: 'ÖNCE KILO (kg)', sweatPost: 'SONRA KILO (kg)',
    sweatFluid: 'ALINAN SIVI (ml)', sweatDur: 'SÜRE (dak)', sweatCalcBtn: 'HESAPLA',
    sweatResult: 'Ter oranınız', sweatReplace: 'egzersiz sırasında %80 yeterliyor',
    raceWeightTitle: 'YARIŞ KİLO HEDEFİ', raceWeightTarget: 'HEDEF KİLO (kg)', raceWeeksTil: 'YARIŞA HAFTA',
    raceWeightSafe: 'Güvenli haftalık kayıp', raceWeightOk: 'Ulaşılabilir', raceWeightAggressive: 'Çok agresif — kas kaybı riski',
    primarySportL: 'ANA SPOR', athleteLevelL: 'SPORCU SEVİYESİ',
    triathlonTypeL: 'TRİATLON MESAFESİ', secondarySportsL: 'İKİNCİL SPORLAR',
    coachCardTitle: 'ANTRENÖRLÜK — HÜSEYİN AKBULUT', connectCoachBtn: 'SPORCU OL',
    connectedCoachMsg: '◈ ANTRENÖRE BAĞLANDI', sendDataCoachBtn: 'VERİ GÖNDER',
    coachConnectNote: 'Antrenman verilerinizi indirin ve antrenörünüze analiz için gönderin.',
    disconnectCoachBtn: 'BAĞLANTI KES',
    // v4.3 intelligence
    insightsTitle: 'ANTRENMAN ANALİZİ', injuryRiskTitle: 'YARALANMA RİSK DEĞERLENDİRMESİ',
    sessionQualityTitle: 'SEANS KALİTESİ', smartAdjTitle: 'AKILLI AYARLAMALAR',
    athleteIntelTitle: 'SPORCU ANALİZİ', copyAnalysisBtn: 'Tam Analizi Kopyala',
    loadTrendLabel: 'YÜK TRENDİ', zoneBalanceLabel: 'ZON DENGESİ',
    fitnessLabel: 'KONDİSYON TAHMİNİ', recovCorrLabel: 'YÜK↔TOPARLANMA',
    // v4.4 storytelling
    weekStoryTitle: 'BU HAFTA\'NIN HİKAYESİ', didYouKnowTitle: 'BİLİYOR MUYDUN?',
    milestoneTitle: 'KİLOMETRE TAŞI!', trainingAgeTitle: 'ANTRENMAN YAŞI',
    nextNoteBtn: 'Sonraki →', shareStoryBtn: '⤴ Paylaş', copyStoryBtn: '⎘ Kopyala',
    trainingAgeLabel: 'Antrenman yaşı', ctlScaleLabel: 'KONDİSYON SKALASI',
    // v5.14 Today View
    t_today: 'BUGÜN',
    todaySession: 'BUGÜNÜN ANTRENMANI', todayRest: 'DİNLENME GÜNÜ', todayDone: 'TAMAMLANDI',
    todayMarkDone: 'TAMAMLANDI İŞARETLE', todayLogThis: 'KAYDET',
    todayNoPlan: 'Aktif plan yok — PLAN sekmesinden oluştur.',
    todayReadiness: 'BUGÜNÜN HAZIRLIĞI', todaySaveReadiness: 'HAZIRLIĞI KAYDET',
    todaySaved: 'KAYDEDİLDİ', todayQuickStats: 'HIZLI İSTATİSTİKLER',
    todayYesterday: 'DÜN', todayThisWeek: 'BU HAFTA', todayConsec: 'SERİ',
    todaySuggestion: 'AKILLI ÖNERİ', todayLogYesterday: '+ Dünü Kaydet',
    // TodayView — coach badge + rings + share
    todayCoachMsg: 'coach\' tan okunmamış mesaj', todayCoachMsgs: 'coach\'tan okunmamış mesajlar',
    todayDismiss: 'KAPAT',
    shareProgress: 'İlerlemeyi Paylaş →',
    weeklyRings: 'HAFTALIK HALKALAR', weekTSS: 'HAFTALIK TSS', wellness: 'SAĞLIK',
    // CoachSquadView
    squadTitle: 'KADRO', loadingSquad: 'Kadro yükleniyor…',
    connected: 'BAĞLI',
    inviteLink: '+ DAVET LİNKİ',
    rtLive: 'Canlı', rtReconnecting: 'Yeniden bağlanıyor…',
    demoDataWarning: 'DEMO VERİSİ — canlı metrikler için gerçek sporcu bağla',
    noAthletesYet: 'Henüz bağlı sporcu yok. Bu davet kodunu paylaş:',
    weeklyDigest: '◈ HAFTALIK ÖZET',
    copyAll: 'TÜMÜNÜ KOPYALA', copied: '✓ KOPYALANDI',
    squadColAthlete: 'SPORCU', squadColReadiness: 'HAZIRLIK',
    squadColTSB: 'TSB', squadColACWR: 'ABYO',
    squadColAdherence: 'UYUM', squadColStatus: 'DURUM',
    squadColFlag: 'İŞARET', squadColMsg: 'MESAJ', squadColCompare: 'KRŞ',
    weeklyRecapDismiss: '[kapat]', weeklyRecapLabel: 'HF',
    // Team Announcements
    teamAnnTitle: 'TAKIM DUYURULARI', teamAnnPost: 'Yayınla', teamAnnPlaceholder: 'Takıma duyuru yaz… (maks. 280 karakter)',
    teamAnnMarkAllRead: 'Tümünü oku', teamAnnUnread: 'okunmamış', teamAnnNone: 'Henüz duyuru yok.',
    teamAnnNoneAthlete: 'Antrenörünüzden henüz duyuru yok.',
    // Quick-Add Session
    quickAddTitle: 'HIZLI ANTRENMAN KAYDET', quickAddSport: 'SPOR', quickAddDuration: 'SÜRE (dak)',
    quickAddRpe: 'ZY (1–10)', quickAddNotes: 'NOT (opsiyonel)', quickAddSave: '+ KAYDET',
    quickAddCancel: 'İptal', quickAddEstTss: 'Tahmini TSS',
    // Keyboard shortcuts
    shortcutsTitle: 'KLAVYE KISAYOLLARI', shortcutsClose: 'Kapat',
    shortcutsNav: 'Gezinme', shortcutsActions: 'Eylemler',
    // Weekly digest notification
    weeklyDigestNotifTitle: 'Haftalık Özet',
    // Reports tab (v7.47)
    t_reports: 'RAPORLAR',
    reportsTitle: 'PDF RAPORLAR', reportsGenerate: 'Oluştur', reportsLocked: 'Kilitli',
    reportsGenerating: 'Oluşturuluyor…', reportsHistory: 'Rapor Geçmişi',
    reportsNoHistory: 'Henüz rapor oluşturulmadı.',
    reportsDownload: 'İndir', reportsDelete: 'Sil', reportsExpired: 'Süresi doldu',
    // Sport Program Builder (C6)
    spb_sport_rowing: 'Kürek', spb_sport_running: 'Koşu', spb_sport_cycling: 'Bisiklet',
    spb_sport_swimming: 'Yüzme', spb_sport_triathlon: 'Triatlon',
    spb_goal_base: 'Taban Kondisyon Geliştir', spb_goal_race: 'Yarışa Hazırlık',
    spb_goal_peak: 'Etkinlik İçin Zirve', spb_goal_maintain: 'Mevcut Seviyeyi Koru',
    spb_title: 'SPOR PROGRAM OLUŞTURUCU',
    spb_sub: 'Monte Carlo optimizer · Banister uyarı-yanıt · 500 simülasyon',
    spb_step1Title: 'SPOR & HEDEF', spb_selectSport: 'SPOR SEÇ', spb_primaryGoal: 'ANA HEDEF',
    spb_raceDate: 'YARIŞ TARİHİ (opsiyonel)', spb_daysToRace: 'yarışa gün kaldı',
    spb_preFilledProfile: '✓ Profilden otomatik dolduruldu',
    spb_step2Title: 'PERFORMANS BAZI',
    spb_fromTestLog: '✓ Test logundan alındı', spb_fromLog: '✓ Logdan alındı',
    spb_fromTrainingData: '✓ Antrenman verisinden alındı', spb_fromLastWeeks: '✓ Son 4 haftadan alındı',
    spb_step3Title: 'ANTRENMAN KISITLARI',
    spb_planDuration: 'Plan Süresi (hafta)', spb_currentTSSLabel: 'Mevcut Haftalık TSS',
    spb_peakTSSLabel: 'Zirve Haftalık TSS Hedefi', spb_currentCTL: 'Mevcut KTY (kondisyon)',
    spb_currentATL: 'Mevcut ATY (yorgunluk)', spb_sessionsPerWeek: 'Seans/hafta (ort.)',
    spb_recoveryAuto: 'Toparlanma haftaları her 4. haftaya otomatik eklenir.',
    spb_step4Title: 'PLAN OLUŞTUR',
    spb_monteCarloSub: 'En yüksek skoru bulmak için 500 Monte Carlo simülasyonu.',
    spb_simulating: 'SİMÜLE EDİLİYOR\u2026', spb_runOptimizer: '\u26a1 OPTİMİZER ÇALIŞTIR',
    spb_btnNext: 'İLERİ \u2192', spb_btnBack: '\u2190 GERİ', spb_generatePlan: 'PLAN OLUŞTUR \u2192',
    spb_step5Title: 'OPTİMİZE EDİLMİŞ PLANIN',
    spb_daysToRaceLabel: 'YARIŞA GÜN', spb_planScore: 'PLAN SKORU', spb_avgScore: 'ORT. SKOR',
    spb_peakForm: 'ZİRVE FORM', spb_peakTSBLabel: 'ZİRVE TSB',
    spb_scoreDistTitle: 'SKOR DAĞILIMI (500 simülasyon)',
    spb_weeklyPlanTitle: 'HAFTALIK PLAN \u2014 PLANLANAN vs GERÇEK',
    spb_exportCSV: '\u2193 CSV', spb_saved: '\u2713 KAYDEDİLDİ', spb_saveToLog: '+ LOGA KAYDET',
    spb_adaptPlan: '\u26a1 PLANI UYARLA', spb_resetPlan: '\u2715 sıfırla',
    spb_colWk: 'HF', spb_colPlanned: 'PLANLANAN', spb_colActual: 'GERÇEK',
    spb_colVariance: 'SAPMA', spb_colSessions: 'SEANSLAR', spb_colDetail: 'DETAY',
    spb_consecutiveWeeks: 'ardışık hafta planda',
    spb_fitnessTrace: 'KONDİSYON / YORGUNLUK İZİ (Banister)',
    spb_ctlLegend: '\u2014 KTY (Kondisyon)', spb_atlLegend: '\u2014 ATY (Yorgunluk)',
    spb_peakFormLegend: '| Zirve form günü',
    spb_comparePlans: '\u21c4 En iyi 2 planı karşılaştır',
    spb_simulateMissed: 'KAÇIRILAN HAFTA SİMÜLASYONU', spb_missedSelectWeek: 'Hafta seç\u2026',
    spb_missWeekBtn: 'Bu haftayı kaçır', spb_missedImpact: 'TSB düşüşü',
    spb_peakFormShifts: 'zirve form kayması', spb_daysLater: 'gün sonraya', spb_daysEarlier: 'gün öncesine',
    spb_buildNewPlan: 'YENİ PLAN OLUŞTUR',
    spb_modalPrint: '\u2399 YAZDIR', spb_modalSessions: 'PLANLANAN SEANSLAR',
    spb_modalTrace: 'GÜNLÜK BANISTER İZİ', spb_modalDay: 'GÜN',
    // Status banner (C5)
    status_outage: null, status_outage_suffix: 'hizmet kesintisi yaşıyor',
    status_degraded: null, status_degraded_suffix: 'yavaşladı \u2014 bazı özellikler geç yanıt verebilir',
    status_check_stale: 'durum kontrolü eskimiş olabilir',
    // Semantic search (C7)
    ssPlaceholder: "Antrenmanlarda anlam ara\u2026 (ör. 'sert interval haftası')",
    ssSearching: 'aranıyor\u2026',
    ssUpgradeMsg: 'Semantik arama Antrenör veya Kulüp planı gerektirir.',
    ssUpgradeLink: 'Yükselt',
    ssRetry: 'Tekrar Dene',
    ssNoResults: 'Eşleşen antrenman bulunamadı. Farklı bir ifade deneyin veya daha fazla not ekleyin.',
    ssMinChars: 'Arama için en az 3 karakter girin.',
    ssIdleTitle: 'Antrenmanlarınızı anahtar kelime değil, anlam ile arayın.',
    ssIdleCorpus: 'Antrenmanlar kaydedildikçe dizine eklenir. Yeni hesaplar ilk hafta içinde veri biriktirir.',
    ssNavHint: '\u2191\u2193 gezin', ssJumpHint: '\u21b5 antrenmana git', ssEscHint: 'Esc kapat',
    ssExample1: 'yarıştan önce sert interval haftası',
    ssExample2: 'düşük nabızla kolay toparlanma koşusu',
    ssExample3: 'dağlarda uzun bisiklet turu',
    ssExample4: 'yorgun hissettim, uyku kötüydü',
    // Global FTS search (P7)
    gsTitle: 'Her Şeyi Ara',
    gsPlaceholder: 'Antrenman, not, mesaj ara\u2026',
    gsSearching: 'aranıyor\u2026',
    gsSemantic: 'semantik \u2192',
    gsRecent: 'Son Aramalar',
    gsNoResults: 'Sonuç bulunamadı. Farklı bir kelime deneyin.',
    gsKind_session: 'Antrenmanlar',
    gsKind_note: 'Notlar',
    gsKind_message: 'Mesajlar',
    gsKind_announcement: 'Duyurular',
    gsKind_athlete: 'Sporcular',
    // Live squad feed (C7)
    feedSquadLabel: 'KADRO AKIŞI',
    feedNoAthletes: 'Henüz sporcu yok \u2014 Kadro sekmesinden ilk sporcunu davet et.',
    feedNoActivity: 'Henüz aktivite yok \u2014 kadro güncellemeleri bekleniyor\u2026',
    feedConnecting: 'Canlı akışa bağlanıyor\u2026',
    feedOnline: '\u00e7evrimii\u00e7i',
    // E11 — session comments + presence
    commentsTitle: 'YORUMLAR',
    commentPlaceholder: 'Yorum ekle\u2026 (maks 2000 karakter)',
    commentPost: 'G\u00d6NDER',
    commentEdit: 'D\u00fczenle',
    commentDelete: 'Sil',
    commentEdited: '(d\u00fczenlendi)',
    commentDeleted: '[silindi]',
    commentReply: 'Yan\u0131tla',
    commentCancel: '\u0130ptal',
    commentSave: 'Kaydet',
    commentEmpty: 'Hen\u00fcz yorum yok.',
    commentOffline: 'Yorum kuyru\u011fa al\u0131nd\u0131 \u2014 \u00e7evrimii\u00e7i olunca g\u00f6nderilecek.',
    coachPresenceViewing: '\u015eu an g\u00f6r\u00fcnt\u00fcl\u00fcyor',
    coachPresenceNever: 'Hen\u00fcz g\u00f6r\u00fcnt\u00fclenmedi',
    coachPresenceLabel: 'ANTREN\u00d6R',
    coachPresenceAthlete: 'SPORCU',
  }
}

// ─── Tabs ──────────────────────────────────────────────────────────────────────
export const TABS = [
  { id: 'today',         icon: '\u25c9', lk: 't_today' },
  { id: 'dashboard',     icon: '\u25c8', lk: 't_dashboard' },
  { id: 'zones',         icon: '\u25c9', lk: 't_zones' },
  { id: 'tests',         icon: '\u25b2', lk: 't_tests' },
  { id: 'log',           icon: '\u2261', lk: 't_log' },
  { id: 'periodization', icon: '\u229e', lk: 't_macro' },
  { id: 'plan',          icon: '\u26a1', lk: 't_plan' },
  { id: 'glossary',      icon: '\u25c7', lk: 't_glossary' },
  { id: 'recovery',      icon: '\u2661', lk: 't_recovery' },
  { id: 'profile',       icon: '\u25cb', lk: 't_profile' },
  { id: 'sport',         icon: '\u25b6', lk: 't_sport' },
  { id: 'reports',       icon: '\u25a4', lk: 't_reports' },
]
