-- ─── 20260413_ai_insights.sql — AI insights cache table ──────────────────────
-- Stores per-athlete daily AI summaries generated by the nightly-batch edge fn.
-- Unique constraint on (athlete_id, date, data_hash) for idempotent upserts.

CREATE TABLE IF NOT EXISTS ai_insights (
  id           BIGSERIAL PRIMARY KEY,
  athlete_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date         DATE NOT NULL,
  data_hash    TEXT NOT NULL,
  insight_json JSONB,
  model        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (athlete_id, date, data_hash)
);

ALTER TABLE ai_insights ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS ai_insights_athlete_date ON ai_insights (athlete_id, date DESC);

COMMENT ON TABLE ai_insights IS 'Daily AI training summaries. Written by nightly-batch edge fn, read by athlete. Tier-gated via 20260413_tier_enforcement.sql.';
