-- ─── 20260417_ai_explanation.sql — Add explanation_text to ai_insights ────────
-- Stores cached Haiku explanation for the "Why?" button on athlete AI summaries.
-- Written lazily on first request; served from cache on subsequent reads.

ALTER TABLE ai_insights ADD COLUMN IF NOT EXISTS explanation_text TEXT;

COMMENT ON COLUMN ai_insights.explanation_text IS
  'Cached plain-language explanation of insight_json, generated by Haiku on demand.';
